//
// Created by qq798 on 2018/8/11.
//

#ifndef MYFFMPEGPLAYER_ENUMCURRENTPLAYSTATE_H
#define MYFFMPEGPLAYER_ENUMCURRENTPLAYSTATE_H

enum EnumCurrentPlayState{
    PLAYING=0,
    EXIT,
    PAUSE,
    SEEKING
};

#endif //MYFFMPEGPLAYER_ENUMCURRENTPLAYSTATE_H
